In [1]:
import numpy as np

In [28]:
arr=np.arange(10)

In [29]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
#これでも一発表示
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
#配列の中の数字を書き換え
arr[3]=5
arr

array([0, 1, 2, 5, 4, 5, 6, 7, 8, 9])

In [34]:
#Numpyの配列もリストと基本的には同じ
list=[0,1,2,3,4]
list

[0, 1, 2, 3, 4]

In [35]:
list[1]=8
list

[0, 8, 2, 3, 4]

In [38]:
arr1=np.arange(8)

for i in range(8):
    arr1[i]=i

arr1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [3]:
np.arange((8,4))

TypeError: arange: scalar arguments expected instead of a tuple.

In [4]:
np.random.randn(8,4)

array([[-0.92442364,  0.12532098, -0.28869535,  0.03818235],
       [-0.419525  ,  0.52237424, -0.77401926,  0.09063418],
       [ 0.98279709, -0.45166779,  0.40171485, -0.3190089 ],
       [-0.05737623,  0.64952759,  1.24337528, -1.68578271],
       [-0.95497332,  0.01220698, -0.88162077,  0.68772623],
       [ 0.82986355, -0.47669615,  3.0221972 , -0.28682667],
       [-1.01176668,  0.69601078, -0.03059154,  0.24269077],
       [ 0.48389459,  1.36194106,  0.84522451,  0.40833163]])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [8]:
arr=np.random.randn(8,4)

In [9]:
for i in range(8):
    arr[i]=i

In [10]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [14]:
arr=np.random.randn(8,4)

▼行の中の列を指定のやり方。

In [47]:
arr[1][2]=99
arr

array([[  0.,   0.,   0.,   0.],
       [  1.,   1.,  99.,   1.],
       [  2.,   2.,   2.,   2.],
       [  3.,   3.,   3.,   3.],
       [  4.,   4.,   4.,   4.],
       [  5.,   5.,   5.,   5.],
       [  6.,   6.,   6.,   6.],
       [  7.,   7.,   7.,   7.]])

In [16]:
for i in range(4):
    arr[0][i]=i

In [17]:
arr

array([[ 0.        ,  1.        ,  2.        ,  3.        ],
       [ 0.70662227, -0.99915314, -0.81775336,  1.28364447],
       [-0.89533139,  0.7884615 , -0.54829446,  1.4293689 ],
       [ 0.05581489, -0.68965639, -1.63850402,  0.24855615],
       [ 0.36550711, -0.35667375, -0.2423336 ,  0.12366919],
       [-0.64581329,  0.15718229,  1.09952074, -1.92002304],
       [-0.92266813, -0.35047346, -0.69122726,  0.08319126],
       [ 0.93287418,  1.17683416, -0.24542741,  0.16698977]])

配列が1次元の場合は、配列の中の1つの数字が入れ替わる。配列が2次元の場合は、配列の数字がまるまる入れ替わる。
じゃあ、配列を2つ指定をすると…

▼ちなみに、行の中の列を指定。これでもオッケー

In [51]:
arr[2,3]=99
arr

array([[  0.,   0.,   0.,   0.],
       [  1.,   1.,  99.,   1.],
       [  2.,   2.,   2.,  99.],
       [  3.,   3.,   3.,   3.],
       [  4.,   4.,   4.,   4.],
       [  5.,   5.,   5.,   5.],
       [  6.,   6.,   6.,   6.],
       [  7.,   7.,   7.,   7.]])

In [52]:
arr.T

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.],
       [  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.],
       [  0.,  99.,   2.,   3.,   4.,   5.,   6.,   7.],
       [  0.,   1.,  99.,   3.,   4.,   5.,   6.,   7.]])

In [28]:
arr=np.arange(20).reshape((5,4))

In [29]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [53]:
for i in range(10):
    arr[i]=i
    
#「arr=np.arange(20).reshape((5,4))」の部分で、5行しかない配列を作っている。一方で、ここで10行の配列を作っているからエラー。5以下にすればオッケー

IndexError: index 8 is out of bounds for axis 0 with size 8

▼meshgridメゾット
meshgridメゾットは、組み合わせを作るメゾット。
[1 2 3]と[4 5 6 7]は、3×4＝12通りの組み合わせがある。
すなわち、(1,4)(1,5)(1,6)(1,7)(2,4)(2,5)(2,6)(2,7)(3,4)(3,5)(3,6)(3,7)の12通り。

例えば、
[1 2 3]と[4 4 4]の1番目ずつの組合せ、2番目ずつのの組合せ、3番目ずつの組合せの3つ。
つまり、(1,4)(2,4)(3,4)の3つ。
[1 2 3]と[5 5 5]も同様に3つ
[1 2 3]と[6 6 6]の同様に3つ
[1 2 3]と[7 7 7]の同様に3つ
で12通りの組み合わせができる。

下記で実行を試す。

In [9]:
data1=np.arange(1,4,1)
print data1

[1 2 3]


In [10]:
data2=np.arange(4,8,1)
print data2

[4 5 6 7]


In [11]:
np.meshgrid(data1,data2)

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), array([[4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7]])]

In [12]:
xs,ys=np.meshgrid(data1,data2)

In [13]:
xs

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [14]:
ys

array([[4, 4, 4],
       [5, 5, 5],
       [6, 6, 6],
       [7, 7, 7]])

配列同士を足し算すると、それぞれの組合せで足し算ができる

In [18]:
xs+ys

array([[ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10]])

In [11]:
data=np.random.randn(10)

In [25]:
data.sort()
print data

[-1.63475376 -0.87706536 -0.07711007  0.19874222  0.20197432  0.21284648
  0.68753392  1.37268372  1.94104556  2.01564524]


In [21]:
#これでもソートができる

In [22]:
np.sort(data)

array([-1.63475376, -0.87706536, -0.07711007,  0.19874222,  0.20197432,
        0.21284648,  0.68753392,  1.37268372,  1.94104556,  2.01564524])

In [24]:
data[::-1].sort()
print data

[ 2.01564524  1.94104556  1.37268372  0.68753392  0.21284648  0.20197432
  0.19874222 -0.07711007 -0.87706536 -1.63475376]


In [ ]:
np.sort(data)[::-1]

In [22]:
xarr=np.array([1,2,3,4,5])

In [23]:
yarr=np.array([6,7,8,9,10])

In [25]:
cond=np.array([True,False,True,False,True])

In [32]:
np.where(cond,xarr,yarr)

array([1, 7, 3, 9, 5])

In [ ]:
2つの配列があれば、if関数のようなことができる。

In [55]:
arr=np.random.randn(12).reshape(4,3)

In [56]:
arr

array([[ 0.17064502, -1.39680721,  0.84478854],
       [-0.5571854 ,  0.31120331, -0.31862856],
       [ 0.72536046, -0.50316589,  0.82451611],
       [ 0.57974968, -0.71880407,  1.48095726]])

In [57]:
np.where(arr>0,2,arr)

array([[ 2.        , -1.39680721,  2.        ],
       [-0.5571854 ,  2.        , -0.31862856],
       [ 2.        , -0.50316589,  2.        ],
       [ 2.        , -0.71880407,  2.        ]])

In [60]:
arr=np.arange(12).reshape(3,4)

In [61]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
np.mean(arr)

5.5

In [63]:
arr.mean()

5.5

In [3]:
arr=np.array([True,False])

In [4]:
arr.any()

True

In [5]:
arr.all()

False

In [6]:
arr=np.array([True,True])

In [7]:
arr.any()

True

In [8]:
arr.all()

True

In [9]:
arr=np.array([False,False])

In [10]:
arr.any()

False

In [11]:
arr.all()

False

In [12]:
arr=np.array([1,1,1,2,3,3])

In [13]:
np.unique(arr)

array([1, 2, 3])

In [ ]:
■ファンシーインデックス

In [10]:
data=np.arange(24).reshape(6,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
#これで1次元
data[1]

array([4, 5, 6, 7])

In [19]:
#1次元を2つ。2行目と4行目
data[[1,3]]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [21]:
#これだと1次元を2つじゃなく、2行目の4番目という意味
data[1,3]

7

In [20]:
#2行目の4番目は、こうやっても書ける
data[[1],[3]]

array([7])

In [23]:
#対になっている
data[[1,4],[0,3]]

array([ 4, 19])

In [24]:
#対になっているので、エラーになる
data[[1,4],[0,3,1]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [33]:
data1=np.random.randn(12).reshape(4,3)
print data1

[[-1.58502419 -0.08750534  0.2424771 ]
 [ 0.19694195  0.22901211  0.38785624]
 [ 0.76346931  1.93834705 -1.62271029]
 [-0.78260724 -0.04858086  1.51557515]]


In [34]:
data2=np.random.randn(15).reshape(3,5)
print data2

[[-1.09529721  0.4347704  -0.37167575  0.31574051 -1.00843905]
 [ 0.33428951 -0.61787001 -0.89804524 -1.10212213 -0.18025446]
 [-0.11148414 -0.75787689  0.25313831 -1.26819151  0.86519957]]


In [36]:
np.meshgrid(data1,data2)

[array([[-1.58502419, -0.08750534,  0.2424771 ,  0.19694195,  0.22901211,
          0.38785624,  0.76346931,  1.93834705, -1.62271029, -0.78260724,
         -0.04858086,  1.51557515],
        [-1.58502419, -0.08750534,  0.2424771 ,  0.19694195,  0.22901211,
          0.38785624,  0.76346931,  1.93834705, -1.62271029, -0.78260724,
         -0.04858086,  1.51557515],
        [-1.58502419, -0.08750534,  0.2424771 ,  0.19694195,  0.22901211,
          0.38785624,  0.76346931,  1.93834705, -1.62271029, -0.78260724,
         -0.04858086,  1.51557515],
        [-1.58502419, -0.08750534,  0.2424771 ,  0.19694195,  0.22901211,
          0.38785624,  0.76346931,  1.93834705, -1.62271029, -0.78260724,
         -0.04858086,  1.51557515],
        [-1.58502419, -0.08750534,  0.2424771 ,  0.19694195,  0.22901211,
          0.38785624,  0.76346931,  1.93834705, -1.62271029, -0.78260724,
         -0.04858086,  1.51557515],
        [-1.58502419, -0.08750534,  0.2424771 ,  0.19694195,  0.22901211,
      

In [22]:
arr=np.array([1,1,1,1,2,3,3,3,4,4,5])

In [24]:
np.unique(arr)

array([1, 2, 3, 4, 5])

In [25]:
arr=np.arange(10)

In [27]:
np.save('some_array',arr)

In [28]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])