In [2]:
import numpy as np
import pandas as pd
from pandas import DataFrame,Series

In [2]:
arr=np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[3]=5

In [6]:
arr

array([0, 1, 2, 5, 4, 5, 6, 7, 8, 9])

In [9]:
list=[0,1,2,3,4]

In [10]:
list[1]=8

In [11]:
list

[0, 8, 2, 3, 4]

In [19]:
for i in range(8):
    arr[i]=i

In [12]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr=np.empty((8,4))

In [14]:
arr

array([[  2.45550626e-321,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000]])

In [ ]:
arr=np.random.randn(8,4)

In [15]:
arr

array([[  2.45550626e-321,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000]])

In [20]:
arr=np.empty((10,4))

In [22]:
for i in range(10):
    arr[i]=i

In [23]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.]])

In [25]:
arr.T

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [28]:
arr=np.arange(20).reshape((5,4))

In [29]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [3]:
for i in range(10):
    arr[i]=i
    
#「arr=np.arange(20).reshape((5,4))」の部分で、5行しかない配列を作っている。一方で、ここで10行の配列を作っているからエラー。5以下にすればオッケー

NameError: name 'arr' is not defined

In [8]:
data1=np.arange(1,4,1)
print data1

[1 2 3]


In [18]:
data2=np.arange(10,15,1)
print data2

[10 11 12 13 14]


In [21]:
x,y=np.meshgrid(data1,data2)

In [11]:
data=np.random.randn(10)

In [25]:
data.sort()
print data

[-1.63475376 -0.87706536 -0.07711007  0.19874222  0.20197432  0.21284648
  0.68753392  1.37268372  1.94104556  2.01564524]


In [21]:
#これでもソートができる

In [22]:
np.sort(data)

array([-1.63475376, -0.87706536, -0.07711007,  0.19874222,  0.20197432,
        0.21284648,  0.68753392,  1.37268372,  1.94104556,  2.01564524])

In [24]:
data[::-1].sort()
print data

[ 2.01564524  1.94104556  1.37268372  0.68753392  0.21284648  0.20197432
  0.19874222 -0.07711007 -0.87706536 -1.63475376]


In [ ]:
np.sort(data)[::-1]

In [22]:
xarr=np.array([1,2,3,4,5])

In [23]:
yarr=np.array([6,7,8,9,10])

In [25]:
cond=np.array([True,False,True,False,True])

In [32]:
np.where(cond,xarr,yarr)

array([1, 7, 3, 9, 5])

In [11]:
arr=np.random.randn(12).reshape(4,3)

In [12]:
arr

array([[ 0.60524836, -1.47278266,  1.77251955],
       [ 1.3508345 , -0.04541456, -0.44688141],
       [ 0.07203824, -0.12516175, -0.82152708],
       [-0.70408336, -1.58749939, -0.78704608]])

In [13]:
np.where(arr>0.5,2,arr)

array([[ 2.        , -1.47278266,  2.        ],
       [ 2.        , -0.04541456, -0.44688141],
       [ 0.07203824, -0.12516175, -0.82152708],
       [-0.70408336, -1.58749939, -0.78704608]])

In [14]:
arr=np.arange(12).reshape(3,4)

In [15]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
np.mean(arr)

5.5

In [18]:
arr.mean()

5.5

In [ ]:
#リストとアレイの違い

In [34]:
i=range(0,4)
i

[0, 1, 2, 3]

In [35]:
j=range(4,7)
j

[4, 5, 6]

In [32]:
k=np.arange(0,4)
k

array([0, 1, 2, 3])

In [33]:
l=np.arange(4,7)
l

array([4, 5, 6])

In [36]:
i[1]

1

In [37]:
j[1]

5

In [38]:
k[1]

1

In [39]:
l[1]

5

In [40]:
np.meshgrid(i,j)

[array([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]), array([[4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6]])]

In [41]:
np.meshgrid(k,l)

[array([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]), array([[4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6]])]

In [42]:
x,y=np.meshgrid(k,l)

In [43]:
x

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [44]:
y

array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])

In [52]:
x,y=np.meshgrid(i,j)
x,y

(array([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]), array([[4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6]]))

In [59]:
x,y=np.meshgrid(j,i)
x,y
#(x,y)の組み合わせを使う。例えば、1番目の1個めは(4,0)次が(5,0),(6,0),(4,1)

(array([[4, 5, 6],
        [4, 5, 6],
        [4, 5, 6],
        [4, 5, 6]]), array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]))

In [60]:
np.random.randint(1,10,10)

In [ ]:
np.random.seed(12345)

In [4]:
#一様乱数
np.random.rand(3)

array([ 0.64292554,  0.19742912,  0.92496731])

In [5]:
#正規分布にもとづく乱数
np.random.randn(3)

array([-1.51907706,  0.01178046, -1.38922427])

In [6]:
#整数の乱数を1個生成
np.random.randint(10)

5

In [7]:
#1～9の間の整数の乱数を1個生成
np.random.randint(1,10)

8

In [8]:
#1～9の間の整数の乱数を3個生成
np.random.randint(1,10,3)

array([5, 8, 9])

In [9]:
np.random.rand(3,3)

array([[ 0.24485507,  0.59451031,  0.69896824],
       [ 0.21437765,  0.44490523,  0.68201679],
       [ 0.60346642,  0.37002936,  0.31804854]])

In [10]:
np.random.randn(3,3)

array([[-0.35599185,  1.33195711, -0.27057085],
       [ 1.26259371,  0.26292275, -0.18594865],
       [-0.39065614,  0.48430306,  0.77144943]])

In [ ]:
#rand、つまり、一様乱数でのヒストグラム
from numpy.random import *
import matplotlib.pyplot as plt

R = rand(1000) 
plt.hist(R, bins=100)   
plt.show()  

In [ ]:
#randn、つまり、正規分布にしたがった乱数でのヒストグラム
from numpy.random import *
import matplotlib.pyplot as plt

R = randn(1000) 
plt.hist(R, bins=100)   
plt.show()  

In [ ]:
#何度実行しても同じ実行結果になる。
np.random.seed(0)
np.random.rand(3)

In [ ]:
#毎回違う実行結果になる。
np.random.rand(3)

In [ ]:
#シードの部分を固定すれば、再現性がある乱数を作れる
np.random.seed(12345)
dframe = DataFrame(np.random.randn(1000,4))
dframe.head()

In [ ]:
np.random.randint(1,5,4)

In [ ]:
#permutationは並び替えという点で上記とは違う
np.random.permutation(4)