In [20]:
import numpy as np
import pandas as pd
from pandas import DataFrame,Series

In [21]:
np.random.randint(1,10,10)

array([3, 3, 7, 5, 3, 9, 4, 7, 9, 5])

In [22]:
np.random.seed(12345)

In [23]:
#一様乱数
np.random.rand(3)

array([ 0.92961609,  0.31637555,  0.18391881])

In [24]:
#正規分布にもとづく乱数
np.random.randn(3)

array([ 0.31616001, -1.379198  ,  0.45055442])

In [25]:
#整数の乱数を1個生成
np.random.randint(10)

9

In [26]:
#1～9の間の整数の乱数を1個生成
np.random.randint(1,10)

8

In [27]:
#1～9の間の整数の乱数を3個生成
np.random.randint(1,10,3)

array([7, 1, 3])

In [28]:
np.random.rand(3,3)

array([[ 0.96130674,  0.0083883 ,  0.10644438],
       [ 0.29870371,  0.65641118,  0.80981255],
       [ 0.87217591,  0.9646476 ,  0.72368535]])

In [29]:
np.random.randn(3,3)

array([[ 0.09267329,  1.35291684,  0.88642934],
       [-2.00163731, -0.37184254,  1.66902531],
       [-0.43856974, -0.53974145,  0.47698501]])

In [30]:
#rand、つまり、一様乱数でのヒストグラム
from numpy.random import *
import matplotlib.pyplot as plt

R = rand(1000) 
plt.hist(R, bins=100)   
plt.show()  

In [31]:
#randn、つまり、正規分布にしたがった乱数でのヒストグラム
from numpy.random import *
import matplotlib.pyplot as plt

R = randn(1000) 
plt.hist(R, bins=100)   
plt.show()  

In [32]:
#何度実行しても同じ実行結果になる。
np.random.seed(0)
np.random.rand(3)

array([ 0.5488135 ,  0.71518937,  0.60276338])

In [33]:
#毎回違う実行結果になる。
np.random.rand(3)

array([ 0.54488318,  0.4236548 ,  0.64589411])

In [34]:
#シードの部分を固定すれば、再現性がある乱数を作れる
np.random.seed(12345)
dframe = DataFrame(np.random.randn(1000,4))
dframe.head()

0         1         2         3
0 -0.204708  0.478943 -0.519439 -0.555730
1  1.965781  1.393406  0.092908  0.281746
2  0.769023  1.246435  1.007189 -1.296221
3  0.274992  0.228913  1.352917  0.886429
4 -2.001637 -0.371843  1.669025 -0.438570

In [42]:
np.random.randint(1,5,4)

array([3, 3, 4, 3])

In [43]:
#permutationは並び替えという点で上記とは違う
np.random.permutation(4)

array([0, 3, 2, 1])